;<?php die('');?>
isWindows=1
enableAllModules=
disableInstallers=
forceHTTPSPort=
forceHTTPPort=
fallbackLocale=
domainName=devweb.localhost
modulesPath="lib:jelix-modules/,app:modules/"
pluginsPath="app:plugins/,lib:jelix-plugins/"
timeZone="Europe/Paris"
httpVersion=
theme=default
charset=UTF-8
locale=en_US
startAction="default:index"
startModule=GiteoWebService
[availableLocales]
0=en_US
[modules]
jelix.access=2
jacldb.access=0
jacl2db.access=0
jauth.access=0
jauthdb.access=0
junittests.access=0
jWSDL.access=0
GiteoWebService.access=2
jelix.dbprofile=default
jacl.access=0
jacl.dbprofile=default
jacl2db.dbprofile=default
jacldb.dbprofile=default
jauth.dbprofile=default
jauthdb.dbprofile=default
junittests.dbprofile=default
jWSDL.dbprofile=default
GiteoWebService.dbprofile=default
[coordplugins]
[tplplugins]
defaultJformsBuilder=html
[responses]
html=myHtmlResponse
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
sitemap=jResponseSitemap
html.path="C:\Users\www\GiteoWebService/responses/myHtmlResponse.class.php"
basichtml.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseBinary.class.php"
text.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXmlrpc.class.php"
xul.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXul.class.php"
xuloverlay.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXulPage.class.php"
rdf.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRdf.class.php"
xml.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXml.class.php"
zip.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseZip.class.php"
rss2.0.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseAtom10.class.php"
css.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseTcpdf.class.php"
soap.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseHtml.class.php"
sitemap.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseSitemap.class.php"
[_coreResponses]
html=jResponseHtml
basichtml=jResponseBasicHtml
redirect=jResponseRedirect
redirectUrl=jResponseRedirectUrl
binary=jResponseBinary
text=jResponseText
cmdline=jResponseCmdline
jsonrpc=jResponseJsonrpc
json=jResponseJson
xmlrpc=jResponseXmlrpc
xul=jResponseXul
xuloverlay=jResponseXulOverlay
xuldialog=jResponseXulDialog
xulpage=jResponseXulPage
rdf=jResponseRdf
xml=jResponseXml
zip=jResponseZip
rss2.0=jResponseRss20
atom1.0=jResponseAtom10
css=jResponseCss
ltx2pdf=jResponseLatexToPdf
tcpdf=jResponseTcpdf
soap=jResponseSoap
htmlfragment=jResponseHtmlFragment
htmlauth=jResponseHtml
sitemap=jResponseSitemap
html.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseHtml.class.php"
basichtml.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseBasicHtml.class.php"
redirect.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRedirect.class.php"
redirectUrl.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRedirectUrl.class.php"
binary.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseBinary.class.php"
text.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseText.class.php"
cmdline.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseCmdline.class.php"
jsonrpc.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseJsonrpc.class.php"
json.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseJson.class.php"
xmlrpc.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXmlrpc.class.php"
xul.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXul.class.php"
xuloverlay.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXulOverlay.class.php"
xuldialog.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXulDialog.class.php"
xulpage.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXulPage.class.php"
rdf.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRdf.class.php"
xml.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseXml.class.php"
zip.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseZip.class.php"
rss2.0.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseRss20.class.php"
atom1.0.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseAtom10.class.php"
css.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseCss.class.php"
ltx2pdf.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseLatexToPdf.class.php"
tcpdf.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseTcpdf.class.php"
soap.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseSoap.class.php"
htmlfragment.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseHtmlFragment.class.php"
htmlauth.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseHtml.class.php"
sitemap.path="C:\Users\www\jelix\lib\jelix/core/response/jResponseSitemap.class.php"
[jResponseHtml]
plugins=debugbar
minifyEntryPoint=minify.php
minifyCSS=
minifyJS=
minifyExcludeCSS=
minifyExcludeJS=jquery.wymeditor.js
[debugbar]
plugins="sqllog,sessiondata,defaultlog"
[error_handling]
messageLogFormat="%date%\t%ip%\t[%code%]\t%msg%\t%file%\t%line%\n\t%url%\n%params%\n%trace%\n\n"
errorMessage="A technical error has occured (code: %code%). Sorry for this inconvenience."
[compilation]
checkCacheFiletime=1
force=
[urlengine]
engine=basic_significant
enableParser=1
multiview=
scriptNameServerVariable=SCRIPT_NAME
pathInfoInQueryParameter=
basePath="/GiteoWebService/www/"
backendBasePath=
checkHttpsOnParsing=1
jelixWWWPath="/GiteoWebService/www/../../jelix/lib/jelix-www/"
jqueryPath="/GiteoWebService/www/../../jelix/lib/jelix-www/jquery/"
defaultEntrypoint=index
entrypointExtension=.php
notfoundAct="jelix~error:notfound"
simple_urlengine_https=
significantFile=urls.xml
urlScript="/GiteoWebService/www/index.php"
urlScriptPath="/GiteoWebService/www/"
urlScriptName=index.php
urlScriptId=index
urlScriptIdenc=index
documentRoot="C:/Users/www"
[simple_urlengine_entrypoints]
index="@classic"
xmlrpc="@xmlrpc"
jsonrpc="@jsonrpc"
rdf="@rdf"
[basic_significant_urlengine_entrypoints]
index=1
xmlrpc=1
jsonrpc=1
rdf=1
[logger]
_all=memory
default=file
error=file
warning=file
notice=file
deprecated=
strict=
debug=
sql=
soap=
[fileLogger]
default=messages.log
error=errors.log
warning=errors.log
notice=errors.log
deprecated=errors.log
strict=errors.log
debug=debug.log
[memorylogger]
default=20
error=10
warning=10
notice=10
deprecated=10
strict=10
debug=20
sql=20
soap=20
[mailLogger]
email="root@localhost"
emailHeaders="Content-Type: text/plain; charset=UTF-8\nFrom: webmaster@yoursite.com\nX-Mailer: Jelix\nX-Priority: 1 (Highest)\n"
[mailer]
webmasterEmail="root@localhost"
webmasterName=
mailerType=mail
hostname=
sendmailPath="/usr/sbin/sendmail"
filesDir="mails/"
smtpHost=localhost
smtpPort=25
smtpSecure=
smtpHelo=
smtpAuth=
smtpUsername=
smtpPassword=
smtpTimeout=10
copyToFiles=
[acl]
driver=
[acl2]
driver=
[sessions]
start=1
shared_session=
name=
storage=
loadClasses=
[forms]
controls.datetime.input=menulists
controls.datetime.months.labels=names
datepicker=default
[datepickers]
default="jelix/js/jforms/datepickers/default/init.js"
[htmleditors]
default.engine.name=wymeditor
default.engine.file[]="jelix/jquery/jquery.js"
default.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
default.config="jelix/js/jforms/htmleditors/wymeditor_default.js"
wymbasic.engine.name=wymeditor
wymbasic.engine.file[]="jelix/jquery/jquery.js"
wymbasic.engine.file[]="jelix/wymeditor/jquery.wymeditor.js"
wymbasic.config="jelix/js/jforms/htmleditors/wymeditor_basic.js"
ckdefault.engine.name=ckeditor
ckdefault.engine.file[]="jelix/ckeditor/ckeditor.js"
ckdefault.config="jelix/js/jforms/htmleditors/ckeditor_default.js"
ckfull.engine.name=ckeditor
ckfull.engine.file[]="jelix/ckeditor/ckeditor.js"
ckfull.config="jelix/js/jforms/htmleditors/ckeditor_full.js"
ckbasic.engine.name=ckeditor
ckbasic.engine.file[]="jelix/ckeditor/ckeditor.js"
ckbasic.config="jelix/js/jforms/htmleditors/ckeditor_basic.js"
[wikieditors]
default.engine.name=wr3
default.wiki.rules=wr3_to_xhtml
default.engine.file="jelix/markitup/jquery.markitup.js"
default.config.path="jelix/markitup/sets/wr3/"
default.image.path="jelix/markitup/sets/wr3/images/"
default.skin="jelix/markitup/skins/simple/style.css"
[zones]
disableCache=
[classbindings]
[imagemodifier]
src_url=
src_path=
cache_url=
cache_path=
[rootUrls]
jelix.cache="cache/"
[langToLocale]
en=en_US
[_allBasePath]
0="C:\Users\www\jelix\lib/jelix-modules/"
1="C:\Users\www\GiteoWebService/modules/"
2="C:\Users\www\GiteoWebService/plugins/auth/"
3="C:\Users\www\GiteoWebService/plugins/coord/"
4="C:\Users\www\GiteoWebService/plugins/db/"
5="C:\Users\www\GiteoWebService/plugins/tpl/"
6="C:\Users\www\jelix\lib/jelix-plugins/cache/"
7="C:\Users\www\jelix\lib/jelix-plugins/kvdb/"
[_autoload_class]
[_autoload_namespace]
[_autoload_classpattern]
[_autoload_includepathmap]
[_autoload_includepath]
[_autoload_namespacepathmap]
[_autoload_autoloader]
[_modulesPathList]
jelix="C:\Users\www\jelix\lib\jelix/core-modules/jelix/"
GiteoWebService="C:\Users\www\GiteoWebService/modules/GiteoWebService/"
[_pluginsPathList_auth]
class="C:\Users\www\jelix\lib\jelix/plugins/auth/class/"
db="C:\Users\www\jelix\lib\jelix/plugins/auth/db/"
ldap="C:\Users\www\jelix\lib\jelix/plugins/auth/ldap/"
lds="C:\Users\www\jelix\lib\jelix/plugins/auth/lds/"
[_pluginsPathList_cache]
db="C:\Users\www\jelix\lib\jelix/plugins/cache/db/"
memcache="C:\Users\www\jelix\lib\jelix/plugins/cache/memcache/"
memcache22="C:\Users\www\jelix\lib\jelix/plugins/cache/memcache22/"
file="C:\Users\www\jelix\lib/jelix-plugins/cache/file/"
[_pluginsPathList_coord]
auth="C:\Users\www\jelix\lib\jelix/plugins/coord/auth/"
autolocale="C:\Users\www\jelix\lib\jelix/plugins/coord/autolocale/"
history="C:\Users\www\jelix\lib\jelix/plugins/coord/history/"
jacl="C:\Users\www\jelix\lib\jelix/plugins/coord/jacl/"
jacl2="C:\Users\www\jelix\lib\jelix/plugins/coord/jacl2/"
magicquotes="C:\Users\www\jelix\lib\jelix/plugins/coord/magicquotes/"
traceexec="C:\Users\www\jelix\lib\jelix/plugins/coord/traceexec/"
zendframework="C:\Users\www\jelix\lib\jelix/plugins/coord/zendframework/"
[_pluginsPathList_db]
mssql="C:\Users\www\jelix\lib\jelix/plugins/db/mssql/"
mysql="C:\Users\www\jelix\lib\jelix/plugins/db/mysql/"
mysqli="C:\Users\www\jelix\lib\jelix/plugins/db/mysqli/"
oci="C:\Users\www\jelix\lib\jelix/plugins/db/oci/"
pgsql="C:\Users\www\jelix\lib\jelix/plugins/db/pgsql/"
sqlite="C:\Users\www\jelix\lib\jelix/plugins/db/sqlite/"
sqlite3="C:\Users\www\jelix\lib\jelix/plugins/db/sqlite3/"
[_pluginsPathList_debugbar]
defaultlog="C:\Users\www\jelix\lib\jelix/plugins/debugbar/defaultlog/"
sessiondata="C:\Users\www\jelix\lib\jelix/plugins/debugbar/sessiondata/"
soaplog="C:\Users\www\jelix\lib\jelix/plugins/debugbar/soaplog/"
sqllog="C:\Users\www\jelix\lib\jelix/plugins/debugbar/sqllog/"
[_pluginsPathList_htmlresponse]
debugbar="C:\Users\www\jelix\lib\jelix/plugins/htmlresponse/debugbar/"
minify="C:\Users\www\jelix\lib\jelix/plugins/htmlresponse/minify/"
[_pluginsPathList_jforms]
html="C:\Users\www\jelix\lib\jelix/plugins/jforms/html/"
htmllight="C:\Users\www\jelix\lib\jelix/plugins/jforms/htmllight/"
[_pluginsPathList_kvdb]
db="C:\Users\www\jelix\lib\jelix/plugins/kvdb/db/"
file2="C:\Users\www\jelix\lib\jelix/plugins/kvdb/file2/"
memcache="C:\Users\www\jelix\lib\jelix/plugins/kvdb/memcache/"
redis="C:\Users\www\jelix\lib\jelix/plugins/kvdb/redis/"
file="C:\Users\www\jelix\lib/jelix-plugins/kvdb/file/"
[_pluginsPathList_logger]
firebug="C:\Users\www\jelix\lib\jelix/plugins/logger/firebug/"
[_tplpluginsPathList_common]
0="C:\Users\www\jelix\lib\jelix/plugins/tpl/common/"
1="C:\Users\www\GiteoWebService/plugins/tpl/common/"
[_tplpluginsPathList_html]
0="C:\Users\www\jelix\lib\jelix/plugins/tpl/html/"
1="C:\Users\www\GiteoWebService/plugins/tpl/html/"
[_tplpluginsPathList_ltx2pdf]
0="C:\Users\www\jelix\lib\jelix/plugins/tpl/ltx2pdf/"
[_tplpluginsPathList_text]
0="C:\Users\www\jelix\lib\jelix/plugins/tpl/text/"
1="C:\Users\www\GiteoWebService/plugins/tpl/text/"
[_tplpluginsPathList_xml]
0="C:\Users\www\jelix\lib\jelix/plugins/tpl/xml/"
[_tplpluginsPathList_xul]
0="C:\Users\www\jelix\lib\jelix/plugins/tpl/xul/"
[_pluginsPathList_urls]
basic_significant="C:\Users\www\jelix\lib\jelix/plugins/urls/basic_significant/"
significant="C:\Users\www\jelix\lib\jelix/plugins/urls/significant/"
simple="C:\Users\www\jelix\lib\jelix/plugins/urls/simple/"
